# -*- coding: utf-8 -*-
"""training_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCTc-EfJZCvAcZNsuxZtXz42vkm4n7v2

# Student Stress Survey: Model Training
XGBoost, Random Forest (Full), Random Forest (Focused Features)

## Imports
"""

from datasets import load_dataset
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

"""## Load"""

df = load_dataset("0xmarvel/student-stress-survey")['train'].to_pandas()

"""## Clean"""

COLS_TO_DROP = [
    'StudentStressSurvey_Id',
    'What Are Your Primary Methods For Retaining Information',
    'How Do You Assess Your Understanding And Retention Of Study Materials',
    'What Challenges Do You Face Most Often When Studying',
    'What Measures Do You Take To Manage Minor Ailments Like Headaches When Studying',
    'Which Types Of Extracurricular Activities Are You InvolvedI n',
]

df = (df
    .map(lambda x: x.strip().lower() if isinstance(x, str) else x)
    .replace(["", " ", "n/a", "none"], np.nan)
    .drop(columns=[c for c in COLS_TO_DROP if c in df.columns])
)

df[df.select_dtypes('number').columns] = df.select_dtypes('number').fillna(df.select_dtypes('number').mean())
df[df.select_dtypes('object').columns] = df.select_dtypes('object').fillna("unknown")

df_clean_copy = df.copy()

"""## Target & Encoding"""

TARGET = 'How Would You Rate Your Stress Level During This Academic Term'

stress_map = {"very low": 1, "low": 2, "moderate": 3, "high": 4, "very high": 5}
y = (df[TARGET]
    .map(stress_map)
    .fillna(3)
    .map(lambda x: 0 if x <= 2 else (1 if x == 3 else 2))
)
X = df.drop(columns=[TARGET])

ordinal_map = {"very low": 0, "low": 1, "moderate": 2, "high": 3, "very high": 4}
ordinal_cols = [
    'How Would You Rate Your Overall Health Currently',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Diet In Terms Of Nutritional Balance',
]
for col in ordinal_cols:
    if col in X.columns:
        X[col] = X[col].map(ordinal_map)

binary_cols = [c for c in X.columns if set(X[c].dropna().unique()) <= {"yes", "no"}]
X[binary_cols] = X[binary_cols].replace({"yes": 1, "no": 0})

X = pd.get_dummies(X, drop_first=True)

"""## Preprocess & Split"""

X = np.nan_to_num(StandardScaler().fit_transform(SimpleImputer().fit_transform(X)))

selector = SelectKBest(f_classif, k=20)
X = selector.fit_transform(X, y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

classes = np.unique(y_train)
class_weights = dict(zip(classes, compute_class_weight('balanced', classes=classes, y=y_train)))

"""## XGBoost"""

sample_weights = np.array([class_weights[label] for label in y_train])

model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1,
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='f1_macro')
print(f"CV F1-macro: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

model.fit(X_train, y_train, sample_weight=sample_weights)
y_pred = model.predict(X_test)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=["Low", "Moderate", "High"]))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=["Low", "Moderate", "High"], cmap="Blues", ax=axes[0])
axes[0].set_title("Confusion Matrix")

importances = model.feature_importances_
top_n = min(15, len(importances))
top_idx = np.argsort(importances)[-top_n:]
axes[1].barh(range(top_n), importances[top_idx], color="steelblue")
axes[1].set_yticks(range(top_n))
axes[1].set_yticklabels([f"Feature {i}" for i in top_idx])
axes[1].set_title("Top Feature Importances")
axes[1].set_xlabel("Importance Score")

plt.tight_layout()
plt.savefig("xgb_results.png", dpi=150)
plt.show()

"""## Random Forest (Full Features)"""

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    class_weight=class_weights,
    random_state=42,
    n_jobs=-1,
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
rf_cv_scores = cross_val_score(rf_model, X_train, y_train, cv=cv, scoring='f1_macro')
print(f"CV F1-macro: {rf_cv_scores.mean():.3f} ± {rf_cv_scores.std():.3f}")

rf_model.fit(X_train, y_train)
rf_y_pred = rf_model.predict(X_test)

print("\nClassification Report:")
print(classification_report(y_test, rf_y_pred, target_names=["Low", "Moderate", "High"]))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ConfusionMatrixDisplay.from_predictions(y_test, rf_y_pred, display_labels=["Low", "Moderate", "High"], cmap="Greens", ax=axes[0])
axes[0].set_title("Confusion Matrix")

importances = rf_model.feature_importances_
top_n = min(15, len(importances))
top_idx = np.argsort(importances)[-top_n:]
axes[1].barh(range(top_n), importances[top_idx], color="seagreen")
axes[1].set_yticks(range(top_n))
axes[1].set_yticklabels([f"Feature {i}" for i in top_idx])
axes[1].set_title("Top Feature Importances")
axes[1].set_xlabel("Importance Score")

plt.tight_layout()
plt.savefig("rf_results.png", dpi=150)
plt.show()

"""## Random Forest (Focused Features)"""

FOCUS_COLS = [
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Health Currently',
    'Are You Involved In Any Extracurricular Activities',
    'How Would You Rate Your Stress Level During This Academic Term',
    'Smartphone',
    'Laptop',
    'Desktop',
]

df_focus = df_clean_copy.map(lambda x: x.strip().lower() if isinstance(x, str) else x)
available_focus = [c for c in FOCUS_COLS if c in df_focus.columns]
X_focus = df_focus[available_focus].copy()

for col in [c for c in ordinal_cols if c in X_focus.columns]:
    X_focus[col] = X_focus[col].map(ordinal_map)

focus_binary_cols = [c for c in X_focus.columns if set(X_focus[c].dropna().unique()) <= {"yes", "no"}]
X_focus[focus_binary_cols] = X_focus[focus_binary_cols].replace({"yes": 1, "no": 0})

X_focus = pd.get_dummies(X_focus, drop_first=True)
X_focus = np.nan_to_num(StandardScaler().fit_transform(SimpleImputer().fit_transform(X_focus)))

X_focus_train, X_focus_test, y_focus_train, y_focus_test = train_test_split(
    X_focus, y, test_size=0.2, random_state=42, stratify=y
)

focus_class_weights = dict(zip(classes, compute_class_weight('balanced', classes=classes, y=y_focus_train)))

rf_focus = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    class_weight=focus_class_weights,
    random_state=42,
    n_jobs=-1,
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
rf_focus_cv_scores = cross_val_score(rf_focus, X_focus_train, y_focus_train, cv=cv, scoring='f1_macro')
print(f"CV F1-macro: {rf_focus_cv_scores.mean():.3f} ± {rf_focus_cv_scores.std():.3f}")

rf_focus.fit(X_focus_train, y_focus_train)
rf_focus_y_pred = rf_focus.predict(X_focus_test)

print("\nClassification Report:")
print(classification_report(y_focus_test, rf_focus_y_pred, target_names=["Low", "Moderate", "High"]))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ConfusionMatrixDisplay.from_predictions(y_focus_test, rf_focus_y_pred, display_labels=["Low", "Moderate", "High"], cmap="Oranges", ax=axes[0])
axes[0].set_title("Confusion Matrix (Focused Features)")

importances = rf_focus.feature_importances_
top_n = min(15, len(importances))
top_idx = np.argsort(importances)[-top_n:]
axes[1].barh(range(top_n), importances[top_idx], color="darkorange")
axes[1].set_yticks(range(top_n))
axes[1].set_yticklabels([f"Feature {i}" for i in top_idx])
axes[1].set_title("Top Feature Importances (Focused Features)")
axes[1].set_xlabel("Importance Score")

plt.tight_layout()
plt.savefig("rf_focus_results.png", dpi=150)
plt.show()

"""## XGBoost (Focused Features)"""

xgb_focus_cols = [
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Health Currently',
    'Are You Involved In Any Extracurricular Activities',
    'How Would You Rate Your Stress Level During This Academic Term',
    'Smartphone',
    'Laptop',
    'Desktop',
]

df_focus_xgb = df_clean_copy.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

available_focus_xgb = [c for c in xgb_focus_cols if c in df_focus_xgb.columns]
X_focus_xgb = df_focus_xgb[available_focus_xgb].copy()

for col in [c for c in ordinal_cols if c in X_focus_xgb.columns]:
    X_focus_xgb[col] = X_focus_xgb[col].map(ordinal_map)

focus_xgb_binary_cols = [c for c in X_focus_xgb.columns if set(X_focus_xgb[c].dropna().unique()) <= {"yes", "no"}]
X_focus_xgb[focus_xgb_binary_cols] = X_focus_xgb[focus_xgb_binary_cols].replace({"yes": 1, "no": 0})

X_focus_xgb = pd.get_dummies(X_focus_xgb, drop_first=True)
X_focus_xgb = np.nan_to_num(StandardScaler().fit_transform(SimpleImputer().fit_transform(X_focus_xgb)))

X_focus_xgb_train, X_focus_xgb_test, y_focus_xgb_train, y_focus_xgb_test = train_test_split(
    X_focus_xgb, y, test_size=0.2, random_state=42, stratify=y
)

focus_xgb_class_weights = dict(zip(classes, compute_class_weight('balanced', classes=classes, y=y_focus_xgb_train)))

xgb_focus_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1,
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
xgb_focus_cv_scores = cross_val_score(xgb_focus_model, X_focus_xgb_train, y_focus_xgb_train, cv=cv, scoring='f1_macro')
print(f"CV F1-macro: {xgb_focus_cv_scores.mean():.3f} ± {xgb_focus_cv_scores.std():.3f}")

xgb_focus_sample_weights = np.array([focus_xgb_class_weights[label] for label in y_focus_xgb_train])
xgb_focus_model.fit(X_focus_xgb_train, y_focus_xgb_train, sample_weight=xgb_focus_sample_weights)
xgb_focus_y_pred = xgb_focus_model.predict(X_focus_xgb_test)

print("\nClassification Report:")
print(classification_report(y_focus_xgb_test, xgb_focus_y_pred, target_names=["Low", "Moderate", "High"]))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ConfusionMatrixDisplay.from_predictions(y_focus_xgb_test, xgb_focus_y_pred, display_labels=["Low", "Moderate", "High"], cmap="Purples", ax=axes[0])
axes[0].set_title("Confusion Matrix (XGBoost Focused Features)")

importances = xgb_focus_model.feature_importances_
top_n = min(15, len(importances))
top_idx = np.argsort(importances)[-top_n:]
axes[1].barh(range(top_n), importances[top_idx], color="indigo")
axes[1].set_yticks(range(top_n))
axes[1].set_yticklabels([f"Feature {i}" for i in top_idx])
axes[1].set_title("Top Feature Importances (XGBoost Focused Features)")
axes[1].set_xlabel("Importance Score")

plt.tight_layout()
plt.savefig("xgb_focus_results.png", dpi=150)
plt.show()

"""## Export Models"""

import joblib

# Save XGBoost Focused Model
joblib.dump(xgb_focus_model, 'xgb_focus_model.joblib')
print("XGBoost focused model exported as 'xgb_focus_model.joblib'")

# Save Random Forest Focused Model
joblib.dump(rf_focus, 'rf_focus_model.joblib')
print("Random Forest focused model exported as 'rf_focus_model.joblib'")

# Save the scaler and imputer for consistent preprocessing during inference
joblib.dump(scaler, 'scaler.joblib')
print("Scaler exported as 'scaler.joblib'")

joblib.dump(imp, 'imputer.joblib')
print("Imputer exported as 'imputer.joblib'")

"""## Deploying Models to a Production API

To use your trained models (`xgb_focus_model.joblib`, `rf_focus_model.joblib`) along with the preprocessors (`scaler.joblib`, `imputer.joblib`) in a production environment, you'll typically follow these steps:

1.  **Environment Setup**: Ensure your production environment has all the necessary libraries installed (`pandas`, `numpy`, `scikit-learn`, `xgboost`, `joblib`, and a web framework like `Flask` or `FastAPI`).

2.  **Load Models and Preprocessors**: At the start of your API service, load the saved `.joblib` files. This ensures that the models and preprocessors are loaded once when the application starts, rather than for each request.

3.  **Define a Prediction Endpoint**: Create an HTTP endpoint (e.g., `/predict`) that will receive incoming data.

4.  **Data Preprocessing**: The incoming data (which will be raw features) must be preprocessed using the exact same `StandardScaler` and `SimpleImputer` that were fit during training. This is crucial for consistent predictions. You should also ensure the feature columns are in the correct order and format (e.g., one-hot encoding for categorical features, handling binary/ordinal features as done in the notebook).

5.  **Make Prediction**: Pass the preprocessed data to the loaded model to get a prediction.

6.  **Return Response**: Format the prediction (and any other relevant information) into a JSON response and send it back to the client.

7.  **Deployment**: Deploy your API service using platforms like Flask, FastAPI, AWS Lambda, Google Cloud Run, Azure App Service, etc.

Below is a basic example using Flask to demonstrate the inference process. You would typically save this code as a Python file (e.g., `app.py`) and run it as a web server.
"""

import joblib
import pandas as pd
import numpy as np
from flask import Flask, request, jsonify
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from xgboost import XGBClassifier # Important: need to import XGBClassifier for joblib to load it correctly
from sklearn.ensemble import RandomForestClassifier # Important: need to import RandomForestClassifier for joblib to load it correctly

app = Flask(__name__)

# --- Load Models and Preprocessors (run once at app startup) ---
try:
    xgb_focus_model = joblib.load('xgb_focus_model.joblib')
    rf_focus_model = joblib.load('rf_focus_model.joblib')
    scaler = joblib.load('scaler.joblib')
    imputer = joblib.load('imputer.joblib')
    print("Models and preprocessors loaded successfully.")
except Exception as e:
    print(f"Error loading models or preprocessors: {e}")
    # In a real application, you might want to exit or handle this more gracefully

# Define the necessary global variables from your notebook for preprocessing
FOCUS_COLS = [
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Health Currently',
    'Are You Involved In Any Extracurricular Activities',
    'Smartphone',
    'Laptop',
    'Desktop',
]

ordinal_map = {"very low": 0, "low": 1, "moderate": 2, "high": 3, "very high": 4}
ordinal_cols = [
    'How Would You Rate Your Overall Health Currently',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Diet In Terms Of Nutritional Balance',
]

# Reconstruct X_dummy.columns to ensure correct feature order for inference
# This is crucial for .reindex() and matching the training columns
# Ideally, you would save these column names during training as well.
# For this example, we'll try to recreate it based on the notebook's logic.
# A more robust solution would be to save `X_dummy.columns.tolist()` during training.

# This part needs to be accurately recreated from the training phase
# For simplicity, let's assume `X_dummy.columns` from the notebook's last execution is available
# In a real scenario, you would save this list along with the models.

# Placeholder for training_columns. This should be derived from the X_dummy.columns
# that was used during the fitting of the scaler and imputer.
# Since we cannot directly access `X_dummy.columns` in this isolated cell,
# we need to ensure this is passed or recreated accurately from the training phase.
# For demonstration, let's assume it's available.

# A more robust solution would involve saving `X_dummy.columns.tolist()` as part of the model export.
# For now, we'll use a simplified version, but be aware of this potential mismatch.
# Example: training_columns = ['Smartphone', 'Laptop', 'Desktop', 'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week_less than 3 hours', ...]

# To get `training_columns` accurately, you would typically save it during training
# For example, `joblib.dump(X_dummy.columns.tolist(), 'training_columns.joblib')`
# and then `training_columns = joblib.load('training_columns.joblib')` here.
# For now, we'll make a simplifying assumption for demonstration purposes.
# In a real production system, ensure `training_columns` perfectly matches the columns
# used when `scaler` and `imputer` were fit.

# The actual X_dummy.columns from the kernel state has 29 columns.
# Let's try to simulate the column list if it were saved:
# This is a simplification; ideally, you save the exact list.
TRAINING_COLUMNS_SIMULATED = [
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Health Currently',
    'Are You Involved In Any Extracurricular Activities',
    'Smartphone',
    'Laptop',
    'Desktop',
    'How Would You Rate Your Overall Health Currently_low',
    'How Would You Rate Your Overall Health Currently_moderate',
    'How Would You Rate Your Overall Health Currently_poor',
    'How Would You Rate Your Overall Health Currently_very high',
    'How Would You Rate Your Overall Health Currently_very good',
    'How Would You Rate Your Overall Health Currently_unknown',
    'How Would You Describe The Quality Of Your Sleep On Most Nights_good',
    'How Would You Describe The Quality Of Your Sleep On Most Nights_poor',
    'How Would You Describe The Quality Of Your Sleep On Most Nights_very good',
    'How Would You Describe The Quality Of Your Sleep On Most Nights_very poor',
    'How Would You Describe The Quality Of Your Sleep On Most Nights_unknown',
    'Are You Involved In Any Extracurricular Activities_yes (go to 2.10)',
    'Are You Involved In Any Extracurricular Activities_volunteer work',
    'Are You Involved In Any Extracurricular Activities_sports',
    'Are You Involved In Any Extracurricular Activities_student government',
    'Are You Involved In Any Extracurricular Activities_clubs (e.g., debate, science)',
    'Are You Involved In Any Extracurricular Activities_other (please specify)',
    'Are You Involved In Any Extracurricular Activities_unknown',
    # Add other one-hot encoded columns that would result from get_dummies
    # This list needs to be *exactly* what `X_dummy.columns` contained after preprocessing
    # from the original training script.
    # For this example, I will use a placeholder and emphasize the importance.
    # A full, accurate list would be much longer based on `X_dummy.columns` in the kernel state.
]

# Let's get the actual `X_dummy.columns` from the kernel state for this example for accuracy.
# In a real deployment, this list would be saved and loaded.
TRAINING_COLUMNS = X_dummy.columns.tolist()

def predict_stress_api(input_data, model, scaler, imputer, focus_cols, ordinal_map, ordinal_cols, training_columns):
    df_in = input_data.copy()
    df_in = df_in.apply(lambda x: x.strip().lower() if isinstance(x, str) else x)

    # Select features
    # Ensure all focus_cols are present, even if some are 'unknown' for new data
    X_in = pd.DataFrame(columns=focus_cols) # Start with all expected columns
    for col in focus_cols:
        if col in df_in.columns:
            X_in[col] = df_in[col]
        else:
            X_in[col] = 'unknown' # Or an appropriate default for missing columns

    # Encode Ordinal
    for col in [c for c in ordinal_cols if c in X_in.columns]:
        X_in[col] = X_in[col].map(ordinal_map)

    # Encode Binary
    focus_binary_cols_inference = [c for c in X_in.columns if set(X_in[c].dropna().unique()) <= {"yes", "no", 0, 1, np.nan}]
    X_in[focus_binary_cols_inference] = X_in[focus_binary_cols_inference].replace({"yes": 1, "no": 0})

    # Handle cases where 'Are You Involved In Any Extracurricular Activities' has 'yes (go to 2.10)' etc.
    # This specific handling should match your notebook's `df_clean_copy` preprocessing.
    # For simplicity, if it's not a binary column, we assume it's one-hot encoded later.
    # If 'Are You Involved In Any Extracurricular Activities' has text, ensure get_dummies handles it.
    X_in['Are You Involved In Any Extracurricular Activities'] = X_in['Are You Involved In Any Extracurricular Activities'].apply(lambda x: 'yes' if 'yes' in str(x) else 'no')
    X_in['Are You Involved In Any Extracurricular Activities'] = X_in['Are You Involved In Any Extracurricular Activities'].replace({'yes':1, 'no':0})

    # Dummies and alignment
    X_in = pd.get_dummies(X_in, drop_first=True)

    # Align with training columns: add missing columns as 0 and remove extra ones
    X_in = X_in.reindex(columns=training_columns, fill_value=0)

    X_proc = imputer.transform(X_in)
    X_scaled = scaler.transform(X_proc)

    prediction = model.predict(X_scaled)
    mapping = {0: "Low", 1: "Moderate", 2: "High"}
    return mapping[prediction[0]]

@app.route('/predict_rf', methods=['POST'])
def predict_rf():
    data = request.get_json(force=True)
    # The incoming data should be a dictionary matching the input features
    # Example: {'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week': '7-9 hours', ...}
    input_df = pd.DataFrame([data])

    try:
        prediction_result = predict_stress_api(
            input_df,
            rf_focus_model,
            scaler,
            imputer,
            FOCUS_COLS,
            ordinal_map,
            ordinal_cols,
            TRAINING_COLUMNS
        )
        return jsonify({'prediction': prediction_result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/predict_xgb', methods=['POST'])
def predict_xgb():
    data = request.get_json(force=True)
    input_df = pd.DataFrame([data])

    try:
        prediction_result = predict_stress_api(
            input_df,
            xgb_focus_model,
            scaler,
            imputer,
            FOCUS_COLS,
            ordinal_map,
            ordinal_cols,
            TRAINING_COLUMNS
        )
        return jsonify({'prediction': prediction_result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# To run this Flask app:
# 1. Save this code as `app.py`
# 2. In your terminal, navigate to the directory where you saved `app.py`
# 3. Run: `python -m flask run`
# 4. For production, you'd use a WSGI server like Gunicorn or uWSGI.

# To test locally using curl:
# curl -X POST -H "Content-Type: application/json" -d '{
#   "On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week": "7-9 hours",
#   "How Would You Describe The Quality Of Your Sleep On Most Nights": "good",
#   "How Would You Rate Your Overall Health Currently": "high",
#   "Are You Involved In Any Extracurricular Activities": "no",
#   "Smartphone": "yes",
#   "Laptop": "yes",
#   "Desktop": "yes"
# }' http://127.0.0.1:5000/predict_rf

"""### Important Considerations for Production:

*   **`TRAINING_COLUMNS`**: The `TRAINING_COLUMNS` list is *critical*. It must contain the exact column names (including one-hot encoded dummy variables) in the exact order that `X_dummy.columns` had when the `scaler` and `imputer` were fitted. **You should save this list during your training phase** (e.g., `joblib.dump(X_dummy.columns.tolist(), 'training_columns.joblib')`) and load it in your API.
*   **Error Handling**: The example has basic error handling. In production, you'd want more robust logging and specific error messages.
*   **Security**: For a public API, consider authentication, input validation, and other security measures.
*   **Scalability**: Flask is good for small-scale projects. For high-traffic APIs, consider `FastAPI` (which is often faster and has built-in data validation) or deploying on serverless platforms that handle scaling automatically.
*   **Dependencies**: Create a `requirements.txt` file listing all Python dependencies (`pandas`, `numpy`, `scikit-learn`, `xgboost`, `Flask`, `joblib`) to ensure your production environment is consistent.

# Inference Test
"""

def predict_stress_focused(input_data, model, scaler, imputer, focus_cols, ordinal_map, ordinal_cols, training_columns):
    """
    input_data: pd.DataFrame with raw columns
    """
    df_in = input_data.copy()
    df_in = df_in.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

    # Select features
    available = [c for c in focus_cols if c in df_in.columns]
    X_in = df_in[available].copy()

    # Encode Ordinal
    for col in [c for c in ordinal_cols if c in X_in.columns]:
        X_in[col] = X_in[col].map(ordinal_map)

    # Encode Binary
    binary = [c for c in X_in.columns if set(X_in[c].dropna().unique()) <= {"yes", "no"}]
    X_in[binary] = X_in[binary].replace({"yes": 1, "no": 0})

    # Dummies and alignment
    X_in = pd.get_dummies(X_in, drop_first=True)
    # Align with training columns: add missing columns as 0 and remove extra ones
    X_in = X_in.reindex(columns=training_columns, fill_value=0)

    X_proc = imputer.transform(X_in)
    X_scaled = scaler.transform(X_proc)

    prediction = model.predict(X_scaled)
    mapping = {0: "Low", 1: "Moderate", 2: "High"}
    return mapping[prediction[0]]

# Re-creating fit objects for demonstration
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

raw_focus = df_clean_copy[available_focus].copy()
for col in [c for c in ordinal_cols if c in raw_focus.columns]:
    raw_focus[col] = raw_focus[col].map(ordinal_map)
raw_focus[focus_binary_cols] = raw_focus[focus_binary_cols].replace({"yes": 1, "no": 0})
X_dummy = pd.get_dummies(raw_focus, drop_first=True)

imp = SimpleImputer().fit(X_dummy)
scaler = StandardScaler().fit(imp.transform(X_dummy))

# Test with a single row
sample_input = df_clean_copy.iloc[[0]]
result = predict_stress_focused(sample_input, rf_focus, scaler, imp, FOCUS_COLS, ordinal_map, ordinal_cols, X_dummy.columns)
print(f"Predicted Stress Level: {result}")
print(f"Actual Stress Level (Encoded): {y.iloc[0]}")

"""### Reference: Available Input Options

Use these values in your `custom_data` dictionary for accurate predictions:

*   **Sleep Hours**:
    * `3-5 hours`, `less than 3 hours`, `5-7 hours`, `7-9 hours`, `more than 9 hours`
*   **Sleep Quality**:
    * `very poor - i rarely have a good night's sleep and consistently wake up feeling unrested.`
    * `poor - i frequently have difficulty sleeping and often wake up feeling tired.`
    * `average - my sleep is interrupted, and i sometimes wake up tired.`
    * `good - i sleep well enough, but occasionally wake up feeling tired.`
    * `very good - i sleep soundly and wake up feeling refreshed.`
*   **Overall Health**:
    * `poor`, `fair`, `moderate`, `good`, `very good`, `excellent`, `low`, `high`, `very high`
*   **Extracurricular Activities**:
    * `yes (go to 2.10)`, `no (go to 3)`, `sports`, `volunteer work`, `music or arts`, `student government`, `clubs (e.g., debate, science)`
*   **Device Usage (Smartphone, Laptop, Desktop)**:
    * Use integers `0` to `5` (representing hours or intensity levels).
"""

# Edit these values to test custom scenarios
custom_data = {
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week': '7-9 hours',
    'How Would You Describe The Quality Of Your Sleep On Most Nights': 'good',
    'How Would You Rate Your Overall Health Currently': 'high',
    'Are You Involved In Any Extracurricular Activities': 'no',
    'Smartphone': 'yes',
    'Laptop': 'yes',
    'Desktop': 'yes'
}

# Convert to DataFrame
custom_df = pd.DataFrame([custom_data])

# Run prediction
prediction = predict_stress_focused(
    custom_df,
    rf_focus,
    scaler,
    imp,
    FOCUS_COLS,
    ordinal_map,
    ordinal_cols,
    X_dummy.columns
)

print(f"Custom Input Prediction: {prediction}")

# List unique options for each focused feature to guide custom input
focus_features = [
    'On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week',
    'How Would You Describe The Quality Of Your Sleep On Most Nights',
    'How Would You Rate Your Overall Health Currently',
    'Are You Involved In Any Extracurricular Activities',
    "How Would You Rate Your Stress Level During This Academic Term",
    'Smartphone',
    'Laptop',
    'Desktop'
]

for col in focus_features:
    if col in df_clean_copy.columns:
        options = df_clean_copy[col].unique()
        print(f"{col}:\n  {list(options)}\n")

print(df.columns.tolist())

"""* `StudentStressSurvey_Id`
* `Textbooks And Course`
* `Online Resources (eg Educational Websites, Ebooks)`
* `Video lectures or tutorials`
* `Audio recording and wildcard`
* `Library Resources`
* `Hostel Doom Room`
* `School Libarary`
* `Study Hall Common Areas`
* `Cafes`
* `Outdoor (Parks, Campus Ground)`
* `Desktop`
* `Laptop`
* `Tablets`
* `Smartphone`
* `Traditional Notes`
* `How Often Do You Take Breaks During A Typical Study Session`
* `What Are Your Primary Methods For Retaining Information`
* `How Do You Assess Your Understanding And Retention Of Study Materials`
* `What Challenges Do You Face Most Often When Studying`
* `On Average How Many Hours Do You Spend Studying Each Day`
* `Are You Involved In Any Extracurricular Activities`
* `Which Types Of Extracurricular Activities Are You InvolvedI n`
* `How Would You Rate Your Overall Health Currently`
* `How Would You Rate Your Stress Level During This Academic Term`
* `To What Extent Do You Believe Stress Affects Your Physical Health`
* `Indicate How Much Academic Workload Contribute to stress`
* `How Pressure To Perform Well In Exams Significantly Impacts My Stress Levels`
* `How Time Constraints Significantly Increase My Stress Levels During Examinations`
* `Lack Of SleepIs A Frequent Issue For Me During Exam Periods`
* `My Eating Habits Worsen During Exam Periods`
* `How Frequently Do You Experience Health Issues Such As Headaches Or Other Minor Ailments`
* `When You Experience These Health Issues How Do They Affect Your Ability To Study`
* `What Measures Do You Take To Manage Minor Ailments Like Headaches When Studying`
* `How Would You Describe The Quality Of Your Sleep On Most Nights`
* `On Average How Many Hours Of Sleep Do You Get On A Typical Night During The School Week`
* `Do You Believe That Your Diet Affects Your Academic Performance`
* `How Would You Rate Your Overall Diet In Terms Of Nutritional Balance`
* `If You Were To Use An Examination Routine Manager How Many Courses Would You Want It To Handle Concurrently`

## Strategies to Decrease Overfitting

Overfitting occurs when a model learns the training data too well, including its noise and random fluctuations, leading to poor generalization on unseen data. Here are several effective strategies to mitigate overfitting:

1.  **More Data**: The simplest and often most effective solution is to increase the amount of training data. A larger, more diverse dataset helps the model learn the true underlying patterns rather than noise.

2.  **Feature Selection**: Reducing the number of input features or selecting only the most relevant ones can help prevent the model from learning from irrelevant or noisy features. Techniques like `SelectKBest` (used in this notebook), Recursive Feature Elimination (RFE), or using domain knowledge are helpful.

3.  **Regularization**: This technique penalizes complex models. By adding a penalty term to the loss function, regularization discourages the model from assigning too much importance to any single feature. Common types include:
    *   **L1 Regularization (Lasso)**: Adds a penalty equal to the absolute value of the magnitude of coefficients. It can lead to sparse models by driving some coefficients to zero, effectively performing feature selection.
    *   **L2 Regularization (Ridge)**: Adds a penalty equal to the square of the magnitude of coefficients. It shrinks the coefficients towards zero but doesn't necessarily make them exactly zero.

4.  **Cross-Validation**: While not directly reducing overfitting, cross-validation (like the `StratifiedKFold` used here) provides a more robust estimate of a model's performance on unseen data, helping you identify if overfitting is occurring. If the model performs well on training folds but poorly on validation folds, it's a sign of overfitting.

5.  **Simpler Models**: Using a less complex model architecture can inherently reduce overfitting. For example, a linear model is less prone to overfitting than a very deep neural network, given the same amount of data.

6.  **Early Stopping**: In iterative training algorithms (like gradient boosting or neural networks), training can be stopped when the model's performance on a validation set starts to degrade, even if its performance on the training set is still improving. This prevents the model from learning noise in the later stages of training.

7.  **Ensemble Methods**: Techniques like Random Forests (which we used here) inherently reduce overfitting by combining predictions from multiple base models. Bagging (like in Random Forests) reduces variance, and boosting can also help if carefully tuned.

8.  **Data Augmentation**: For tasks like image or text processing, creating new training samples by applying transformations (e.g., rotation, translation, synonym replacement) to existing data can increase the dataset size and diversity without collecting new data.

9.  **Dropout (for Neural Networks)**: A regularization technique where randomly selected neurons are ignored during training. This forces the network to learn more robust features that are not dependent on the presence of any single neuron.
"""